name: scgpt_finetune
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base[version='>=4.2']
  - r-devtools
  - python=3.9
  - cudatoolkit=11.7
  - numpy=1.21.6
  - matplotlib=3.6.*
  - chardet
  - charset-normalizer
  - zarr
  - pip>=22.3,<=23.2
#  - pip:
#      - -r requirements_1.txt
