name: scgpt_cu124
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - cuda-nvcc=12.4
  - cuda-version=12.4
  - torchtext=0.18.*
  - matplotlib
  - h5py
  - hdf5
  - fsspec=2024.9.0
  - chardet
  - charset-normalizer
  - faiss-gpu=1.9.0
  - r-base[version='>=4.2']
  - r-devtools
  - pip
#  - pip:
#      - -r requirements_1_cu124.txt
#      - -r requirements_2_cu124.txt
